# name: "Pull Request Docs Check"

# on:
#   push:
#     branches:
#       - master

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: make folder
#       run: |
#         mkdir /tmp/sphinx-log
#     - uses: ammaraskar/sphinx-action@master
#       with:
#         docs-folder: "docs/"



# name: Sphinx build

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build HTML
#       uses: ammaraskar/sphinx-action@0.4
#     - name: Upload artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: html-docs
#         path: docs/build/html/
#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v3
#       if: github.ref == 'refs/heads/main'
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: docs/build/html